application: tennismatch-1314
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /templates
  static_dir: templates

- url: /img
  static_dir: img

- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico

- url: /
  static_files: dashboard.html
  upload: dashboard\.html
  secure: always

- url: /login
  static_files: login.html
  upload: login\.html
  secure: always

- url: /create_account
  static_files: create_account.html
  upload: create_account\.html
  secure: always

- url: /profile
  static_files: profile.html
  upload: profile\.html
  secure: always

- url: /email_verif
  static_files: email_verif.html
  upload: email_verif\.html
  secure: always

- url: /forgot_pw
  static_files: forgot_pw.html
  upload: forgot_pw\.html
  secure: always

- url: /reset_pw
  static_files: reset_pw.html
  upload: reset_pw\.html
  secure: always

- url: /about
  static_files: about.html
  upload: about\.html
  secure: always

- url: /_ah/spi/.*
  script: main.api
  secure: always

# Admin console
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

libraries:

- name: endpoints
  version: latest

# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest

# Only using its urlquote function for now
- name: django
  version: latest
