application: tennismatch-1314
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /
  static_files: dashboard.html
  upload: dashboard\.html
  secure: always

- url: /dashboard
  static_files: dashboard.html
  upload: dashboard\.html
  secure: always

- url: /login
  static_files: login.html
  upload: login\.html
  secure: always

- url: /signup
  static_files: signup.html
  upload: signup\.html
  secure: always

- url: /profile
  static_files: profile.html
  upload: profile\.html
  secure: always

- url: /req_match
  static_files: req_match.html
  upload: req_match\.html
  secure: always

- url: /conf_match
  static_files: conf_match.html
  upload: conf_match\.html
  secure: always

- url: /pend_match
  static_files: pend_match.html
  upload: pend_match\.html
  secure: always

- url: /avail_match
  static_files: avail_match.html
  upload: avail_match\.html
  secure: always

- url: /_ah/spi/.*
  script: main.api
  secure: always

libraries:

- name: endpoints
  version: latest

# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest
